@extends('layouts.app')
@section('title', 'Team')
@section('heading', 'Team & Roles')
@section('subheading', 'Owner, manager, technician, accountant, agent, and viewer access')
@section('content')
<div class="row g-4"><div class="col-xl-8"><div class="card metric-card">
<x-filter-bar :action="route('team.index')" :active="$filtered">
    <div class="col-md-5"><input class="form-control form-control-sm" name="search" value="{{ $filters['search'] }}" placeholder="Name or email"></div>
    <div class="col-md-4"><select class="form-select form-select-sm" name="role"><option value="">All roles</option>@foreach($roles as $role)<option value="{{ $role->value }}" @selected($filters['role'] === $role->value)>{{ ucfirst($role->value) }}</option>@endforeach</select></div>
</x-filter-bar>
<div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Member</th><th>Joined</th><th>Role</th></tr></thead><tbody>@forelse($members as $member)<tr><td><strong>{{ $member->name }}</strong><div class="small text-secondary">{{ $member->email }}</div></td><td>{{ $member->pivot->joined_at ? \Carbon\Carbon::parse($member->pivot->joined_at)->format('d M Y') : 'N/A' }}</td><td><form class="d-flex gap-2" method="POST" action="{{ route('team.update', $member) }}">@csrf @method('PATCH')<select class="form-select form-select-sm" name="role">@foreach($roles as $role)<option value="{{ $role->value }}" @selected($member->pivot->role === $role->value)>{{ ucfirst($role->value) }}</option>@endforeach</select><button class="btn btn-sm btn-hotfii">Save</button></form></td></tr>@empty<tr><td colspan="3" class="text-center py-5 text-secondary">{{ $filtered ? 'No members match these filters.' : 'No team members yet.' }}</td></tr>@endforelse</tbody></table></div></div></div><div class="mt-3">{{ $members->links() }}</div></div>
<div class="col-xl-4"><div class="card metric-card"><div class="card-header"><h2 class="h5 mb-0">Add registered user</h2></div><div class="card-body"><p class="text-secondary">The person must already have a HotFii account. Invitation email support can be added after the pilot.</p><form method="POST" action="{{ route('team.store') }}">@csrf<div class="mb-3"><label class="form-label">Email</label><input class="form-control" type="email" name="email" required></div><div class="mb-3"><label class="form-label">Role</label><select class="form-select" name="role">@foreach($roles as $role)<option value="{{ $role->value }}">{{ ucfirst($role->value) }}</option>@endforeach</select></div><button class="btn btn-hotfii w-100">Add team member</button></form></div></div></div></div>
@endsection
