<?php

namespace Tests\Feature\Platform;

use Illuminate\Support\Facades\Route;
use Tests\TestCase;

/**
 * The console is read-only on purpose, and this test is the record of that.
 *
 * Every page that shows money or accounts shows it and stops there: billing
 * plans, trials, invoices and admin rights all change what somebody owes or can
 * see, and a mis-click in a support console would be invisible. Those changes
 * stay server-side. So the check is not "does the button work" but "is the route
 * still absent" — the way this decision erodes is one convenient endpoint at a
 * time. If you are adding a write here deliberately, add it to the allowlist
 * below and say why.
 */
class ConsoleReadOnlyTest extends TestCase
{
    /**
     * The only writes the console is allowed to have.
     */
    private const ALLOWED_WRITES = [
        'platform.organizations.status',
        'platform.payment.approve',
        'platform.payment.reject',
        'platform.impersonate.start',
        'platform.impersonate.stop',
    ];

    private const WRITE_VERBS = ['POST', 'PUT', 'PATCH', 'DELETE'];

    public function test_the_console_has_no_write_routes_beyond_the_allowlist(): void
    {
        $writes = [];

        foreach (Route::getRoutes() as $route) {
            $name = $route->getName();

            if ($name === null || ! str_starts_with($name, 'platform.')) {
                continue;
            }

            if (array_intersect($route->methods(), self::WRITE_VERBS) !== []) {
                $writes[] = $name;
            }
        }

        sort($writes);
        $allowed = self::ALLOWED_WRITES;
        sort($allowed);

        $this->assertSame($allowed, array_values(array_unique($writes)));
    }

    /**
     * The named endpoints somebody will eventually be tempted to add. Each one
     * is spelled out so the reason it is missing survives in writing.
     */
    public function test_the_routes_that_must_not_exist_do_not(): void
    {
        $forbidden = [
            // Invoices are generated by GenerateMonthlyInvoices and settled
            // against the bank, not ticked off in a browser.
            'platform.invoices.update',
            'platform.invoices.pay',
            'platform.billing.generate',
            // Plans and trials change what a customer owes.
            'platform.organizations.update',
            'platform.billing.update',
            // A platform admin can impersonate every tenant, so the flag is
            // granted from a shell with hotfii:create-admin and nowhere else.
            'platform.users.update',
            'platform.users.admin',
            // Pricing is read from config/hotfii.php.
            'platform.pricing.update',
            // Failed jobs are listed, and retried with queue:retry.
            'platform.jobs.retry',
            // A replayed webhook can double-credit a sale.
            'platform.webhooks.replay',
            // Deleting a tenant destroys its financial history.
            'platform.organizations.destroy',
        ];

        foreach ($forbidden as $name) {
            $this->assertFalse(Route::has($name), "Route {$name} exists. The console is read-only there on purpose.");
        }
    }
}
