<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Payment status · HotFii</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="portal-shell py-4"><div class="container"><div class="card portal-card mx-auto"><div class="card-body p-4 p-md-5 text-center">
@if($transaction->status->value === 'successful' && $credential)
<div class="success-ring mx-auto mb-4"><i class="bi bi-check-lg"></i></div><h1 class="h3">Payment confirmed</h1><p class="text-secondary">₦{{ number_format($transaction->gross_amount_kobo/100,0) }} paid for {{ $transaction->accessPlan?->name }}.</p>
@if($allowance)<div class="row g-2 text-start my-4">@if($allowance['remaining_seconds'] !== null)<div class="col-6"><div class="p-3 bg-body-tertiary rounded"><div class="small text-secondary">Time remaining</div><strong>{{ gmdate('H:i:s', $allowance['remaining_seconds']) }}</strong></div></div>@endif @if($allowance['remaining_bytes'] !== null)<div class="col-6"><div class="p-3 bg-body-tertiary rounded"><div class="small text-secondary">Data remaining</div><strong>{{ number_format($allowance['remaining_bytes']/1048576,1) }} MB</strong></div></div>@endif</div>@endif
@if(($transaction->metadata['link_login'] ?? null))<form method="POST" action="{{ $transaction->metadata['link_login'] }}"><input type="hidden" name="username" value="{{ $credential->username }}"><input type="hidden" name="password" value="{{ $credential->password_cipher }}"><input type="hidden" name="dst" value="{{ $transaction->metadata['link_orig'] ?? '' }}"><button class="btn btn-hotfii btn-lg w-100">Connect to Internet</button></form>
@else<div class="alert alert-info text-start"><strong>Laboratory credentials</strong><div class="font-monospace mt-2">Username: {{ $credential->username }}<br>Password: {{ $credential->password_cipher }}</div></div>@endif
@elseif($transaction->status->value === 'failed')<div class="text-danger fs-1"><i class="bi bi-x-circle"></i></div><h1 class="h3">Payment failed</h1><p class="text-secondary">No access was activated. You can safely return and try again.</p><a class="btn btn-outline-secondary" href="{{ route('portal.show',$device) }}">Return to plans</a>
@else<div class="spinner-border text-success mb-4" role="status"></div><h1 class="h3">Confirming payment</h1><p class="text-secondary">This normally takes a few seconds. Keep this page open.</p><div id="pending-note" class="small text-secondary">Reference {{ $transaction->reference }}</div>@endif
</div></div></div>
@if($transaction->status->value === 'pending')<script>setInterval(async function(){const response=await fetch(@json(route('portal.payment.poll',[$device,$transaction])),{headers:{Accept:'application/json'}});if(response.ok){const data=await response.json();if(data.redirect)window.location.assign(data.redirect);if(data.status==='failed')window.location.reload();}},3000);</script>@endif
</body></html>